spring.application.name=ProgInz_Course_Project

#Konfiguracija ar MySQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/miniunips
spring.datasource.username=userspring
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name =com.mysql.jdbc.Driver